name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: haskell/actions/setup@v1.2.1
        with:
          ghc-version: 8.10.4

      - name: cabal cache
        uses: actions/cache@v2.1.5
        with:
          path: |
            ~/.cabal/packages
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-${{ matrix.ghc }}

      - name: Build the package
        run: cabal build

      - name: Prepare test env
        run: |
          mkdir -p $HOME/.config
          mkdir -p $HOME/.local/share

      - name: Test the package
        run: cabal test
